version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install jq -y
  build:
    commands:
      - cd django
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Testing docker image...
      - docker run --rm --entrypoint=/usr/src/app/manage.py $REPOSITORY_URI:$IMAGE_TAG test
    finally:
      - cd ..
      - echo Test completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - aws ecs describe-task-definition --task-definition green-blue-ecs-example | jq '.taskDefinition' > taskdef.json
      - envsubst < appspec_template.yaml > appspec.yaml
artifacts:
  files:
    - appspec.yaml
    - taskdef.json
